### PR TITLE
SOLAS-5225: As a DEVELOPER I am able to publish the component to npm in an efficient manner

### PR DESCRIPTION
**Pull request by robinedman**
https://bcdigital.atlassian.net/browse/SOLAS-5225

Adds the ability to publish the component to npm. See instructions in `README.md`. Adds  an `index.js` entry file that exports the `QuizContainer` component by default and `Quiz` for those who would like to write their own container component.

You can find the published component at https://www.npmjs.com/package/react-quiz
## Testing

You can try publishing a `patch` version yourself to verify that it works. We're currently on `v0.0.3` (so you would publish `v0.0.4`). After we've merged this branch we can release `1.0.0`.

### CODE REVIEW

**Comment by LucjaWszola** [comment]
Hiya, we reviewed this together with @andreadsw and @robinedman :).
We updated the package version and published the newest version of quiz to the public!

**Comment by LucjaWszola** [comment]
README is not updated in dist.

**Comment by andreadsw** [comment]
The version needs to be update automatically. Currently, the version was done manually.

**Comment by robinedman** [comment]
@LucjaWszola @andreadsw Thanks for the comments! Should be fixed now. I've written new instructions in the README. Would be great if you could have a look, and also if you could try making another `patch` release

**Comment by andreadsw** [comment]
Reviewing again ...

**Comment by andreadsw** [comment]
@robinedman Thanks for going through with me on the publish react-quiz process.
- I followed instructions on the readme.md. All fine.👍 
- Released and published `0.0.4` on `www.npmjs.com` with our credentials 👍 
- Updated comments on the readme.md file 👍 

react-quiz-publish-process

**Comment by robinedman** [comment]
Thanks for reviewing again @andreadsw! Merging.

**Pull request merged**
