### PR TITLE
Multiline question

### PR DESCRIPTION
**Pull request by robinedman**
**_minor_ version change**

Adds the ability to have multi-line questions by passing an array of lines instead of a string.

### CODE REVIEW

**Comment by andreadsw** [comment]
It works for me. 👍  It is really flexible the way of use `React.PropTypes.oneOfType` then you have an object that could be one of many types. Cool. 🍉 

react-quiz-multiple-line

**Comment by robinedman** [comment]
Thanks Andrea! Yes that's pretty neat isn't it? That one was new to me as well :)

**Comment by dakala** [comment]
@robinedman Just had a play, added a 3-line question. It works! 👍

**Comment by robinedman** [comment]
@dakala Wow! :) Thanks for checking it out

**Comment by LucjaWszola** [comment]
And I added 4 lines. Now we can write an essay! :)
Nice work @robinedman 👍 

react-quiz

**Review by LucjaWszola — APPROVED** [review]

**Comment by robinedman** [comment]
@LucjaWszola Haha :)

**Pull request merged**
