### PR TITLE
As a USER I would like the ability to select an answer from a pre-defined set of answers

### PR DESCRIPTION
**Pull request by robinedman**
screen shot 2016-06-03 at 16 46 32

Based on https://github.com/britishcouncil/react-quiz/pull/1. To see what's changed, [see comparison](https://github.com/britishcouncil/react-quiz/compare/project-setup...solas-5208-select-answer?expand=1
![screen shot 2016-06-03 at 16 46 32]%28https://cloud.githubusercontent.com/assets/1936213/15784534/dbb95702-29aa-11e6-8f9f-00260b957c5e.png%29).

Please don't review the styling as this component is "styleless". We apply some styling in the included demo app for testing purposes. There's an upcoming story to enable styling the quiz (e.g. using the British Council SUI CSS library).

To start demo app:

```
npm start
```

To run unit tests:

```
npm test
```

[Internal JIRA story](https://bcdigital.atlassian.net/browse/SOLAS-5208)

### CODE REVIEW

**Comment by LucjaWszola** [comment]
Hiya @robinedman I had to clone the repo first, but all went fine and it looks as expected. 👍 

quiz

**Comment by LucjaWszola** [comment]
npm test

test

**Comment by andreadsw** [comment]
Reviewing this one too ...

**Comment by andreadsw** [comment]
@robinedman I checked on browsers such as Chrome, Firefox, Safari and IE9 above. It looks good. Also I checked on couple of devices as ipads and smartphones. 👍

**Comment by mnapthine** [comment]
Looks good 👍

**Pull request merged**
