### PR TITLE
SOLAS-5226: react-quiz - As a USER I can see my progress through the quiz

### PR DESCRIPTION
**Pull request by andreadsw**
Jira ticket: [SOLAS-5226](https://bcdigital.atlassian.net/browse/SOLAS-5226)

Check on this diff since this story branches off #5 : [LINK](https://github.com/britishcouncil/react-quiz/compare/solas-5224-user-answered-all-questions...solas-5226-progress-bar?expand=1)
- Adds a progress bar.
- Adds a counter ("Question 1 of 2").
- Refactors how you set className dynamically and tidies up a bit. 

How to assert it? 
- Assert if the progress bar is presented on the page
- Assert if the progress bar is updated accordingly when you press the "Next" button.
- Assert if all tests are passed.

### CODE REVIEW

**Comment by LucjaWszola** [comment]
@andreadsw and @robinedman everything is in place. 👍 
I tried to read the code @robinedman it makes sense most of the time. Sometimes is more like magic, but I don't mind. :)

quiz

**Comment by robinedman** [comment]
Great! Thanks for that @LucjaWszola, you'll soon be a JavaScript wizard :)

**Comment by mnapthine** [comment]
Looks good to me guys! 👍

**Comment by robinedman** [comment]
Thanks for the review @mnapthine! Merging

**Pull request merged**
