### PR TITLE
SOLAS-5224: react-quiz - As a DEVELOPER I know when the USER has answered all questions AND I have access to the answers

### PR DESCRIPTION
**Pull request by 2creative**
https://bcdigital.atlassian.net/browse/SOLAS-5224

When the user reaches the end and clicks on the finish button, the button runs a function with callback to answers. This story implements this functionality.

There is also a test script to test this.

To run:
npm start

To test:
npm test -- --watch

localhost_3000

### CODE REVIEW

**Comment by andreadsw** [comment]
Reviewing ....

**Comment by andreadsw** [comment]
@2creative @robinedman All good here. 👍 

react-quiz-answers

react-quiz-answers-tests

**Comment by LucjaWszola** [comment]
Same for me, tests passed. 👍 

quiz

**Comment by 2creative** [comment]
Thanks for the reviews guys, @robinedman I think this is ready?

**Comment by robinedman** [comment]
Thanks for the reviews, yes I think it's ready. Merging.

**Pull request merged**
