### PR TITLE
Remove title and rename onFinished to onFinish

### PR DESCRIPTION
**Pull request by robinedman**
Note: Since this breaks the API we provide we should bump the major version after merging.

Also see https://github.com/britishcouncil/tiger-quiz/pull/3

### CODE REVIEW

**Comment by gabemartinez** [comment]
Unrelated: If you're interested, I built a react/redux quiz that was inspired by many examples I found on GitHub; including yours. https://github.com/gabemartinez/trivia

**Comment by andreadsw** [comment]
Reviewing ...

**Comment by robinedman** [comment]
@gabemartinez Great to hear you found this repo useful!

**Comment by andreadsw** [comment]
@robinedman Everything looks good to me. 👍 

react-quiz-ok

**Pull request merged**
